jobs:
  build:
    docker:
      - image: 31482281/codespace:latest
    steps:
      - checkout
      - setup_remote_docker:
         docker_layer_caching: true
      - run:
         name: Run script to start building kernel
         command: ./kbuild.sh
